// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/woocoos/adminx/ent/app"
	"github.com/woocoos/adminx/ent/appmenu"
	"github.com/woocoos/adminx/ent/apppermission"
	"github.com/woocoos/adminx/ent/organization"
	"github.com/woocoos/adminx/ent/organizationuser"
	"github.com/woocoos/adminx/ent/user"
	"github.com/woocoos/adminx/ent/userdevice"
	"github.com/woocoos/adminx/ent/useridentity"
	"github.com/woocoos/adminx/ent/userloginprofile"
	"github.com/woocoos/adminx/ent/userpassword"
	"github.com/woocoos/adminx/graph/entgen/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appMixin := schema.App{}.Mixin()
	appMixinHooks1 := appMixin[1].Hooks()
	app.Hooks[0] = appMixinHooks1[0]
	app.Hooks[1] = appMixinHooks1[1]
	appMixinFields0 := appMixin[0].Fields()
	_ = appMixinFields0
	appMixinFields1 := appMixin[1].Fields()
	_ = appMixinFields1
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescCreatedAt is the schema descriptor for created_at field.
	appDescCreatedAt := appMixinFields1[1].Descriptor()
	// app.DefaultCreatedAt holds the default value on creation for the created_at field.
	app.DefaultCreatedAt = appDescCreatedAt.Default.(func() time.Time)
	// appDescUpdatedAt is the schema descriptor for updated_at field.
	appDescUpdatedAt := appMixinFields1[3].Descriptor()
	// app.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	app.DefaultUpdatedAt = appDescUpdatedAt.Default.(func() time.Time)
	// app.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	app.UpdateDefaultUpdatedAt = appDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appDescName is the schema descriptor for name field.
	appDescName := appFields[0].Descriptor()
	// app.NameValidator is a validator for the "name" field. It is called by the builders before save.
	app.NameValidator = appDescName.Validators[0].(func(string) error)
	// appDescRedirectURI is the schema descriptor for redirect_uri field.
	appDescRedirectURI := appFields[2].Descriptor()
	// app.RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	app.RedirectURIValidator = appDescRedirectURI.Validators[0].(func(string) error)
	// appDescAppSecret is the schema descriptor for app_secret field.
	appDescAppSecret := appFields[4].Descriptor()
	// app.AppSecretValidator is a validator for the "app_secret" field. It is called by the builders before save.
	app.AppSecretValidator = appDescAppSecret.Validators[0].(func(string) error)
	// appDescScopes is the schema descriptor for scopes field.
	appDescScopes := appFields[5].Descriptor()
	// app.ScopesValidator is a validator for the "scopes" field. It is called by the builders before save.
	app.ScopesValidator = appDescScopes.Validators[0].(func(string) error)
	// appDescID is the schema descriptor for id field.
	appDescID := appMixinFields0[0].Descriptor()
	// app.DefaultID holds the default value on creation for the id field.
	app.DefaultID = appDescID.Default.(func() int)
	appmenuMixin := schema.AppMenu{}.Mixin()
	appmenuMixinHooks1 := appmenuMixin[1].Hooks()
	appmenuHooks := schema.AppMenu{}.Hooks()
	appmenu.Hooks[0] = appmenuMixinHooks1[0]
	appmenu.Hooks[1] = appmenuMixinHooks1[1]
	appmenu.Hooks[2] = appmenuHooks[0]
	appmenuMixinFields0 := appmenuMixin[0].Fields()
	_ = appmenuMixinFields0
	appmenuMixinFields1 := appmenuMixin[1].Fields()
	_ = appmenuMixinFields1
	appmenuFields := schema.AppMenu{}.Fields()
	_ = appmenuFields
	// appmenuDescCreatedAt is the schema descriptor for created_at field.
	appmenuDescCreatedAt := appmenuMixinFields1[1].Descriptor()
	// appmenu.DefaultCreatedAt holds the default value on creation for the created_at field.
	appmenu.DefaultCreatedAt = appmenuDescCreatedAt.Default.(func() time.Time)
	// appmenuDescUpdatedAt is the schema descriptor for updated_at field.
	appmenuDescUpdatedAt := appmenuMixinFields1[3].Descriptor()
	// appmenu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appmenu.DefaultUpdatedAt = appmenuDescUpdatedAt.Default.(func() time.Time)
	// appmenu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appmenu.UpdateDefaultUpdatedAt = appmenuDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appmenuDescName is the schema descriptor for name field.
	appmenuDescName := appmenuFields[3].Descriptor()
	// appmenu.NameValidator is a validator for the "name" field. It is called by the builders before save.
	appmenu.NameValidator = appmenuDescName.Validators[0].(func(string) error)
	// appmenuDescID is the schema descriptor for id field.
	appmenuDescID := appmenuMixinFields0[0].Descriptor()
	// appmenu.DefaultID holds the default value on creation for the id field.
	appmenu.DefaultID = appmenuDescID.Default.(func() int)
	apppermissionMixin := schema.AppPermission{}.Mixin()
	apppermissionMixinHooks1 := apppermissionMixin[1].Hooks()
	apppermissionHooks := schema.AppPermission{}.Hooks()
	apppermission.Hooks[0] = apppermissionMixinHooks1[0]
	apppermission.Hooks[1] = apppermissionMixinHooks1[1]
	apppermission.Hooks[2] = apppermissionHooks[0]
	apppermissionMixinFields0 := apppermissionMixin[0].Fields()
	_ = apppermissionMixinFields0
	apppermissionMixinFields1 := apppermissionMixin[1].Fields()
	_ = apppermissionMixinFields1
	apppermissionFields := schema.AppPermission{}.Fields()
	_ = apppermissionFields
	// apppermissionDescCreatedAt is the schema descriptor for created_at field.
	apppermissionDescCreatedAt := apppermissionMixinFields1[1].Descriptor()
	// apppermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	apppermission.DefaultCreatedAt = apppermissionDescCreatedAt.Default.(func() time.Time)
	// apppermissionDescUpdatedAt is the schema descriptor for updated_at field.
	apppermissionDescUpdatedAt := apppermissionMixinFields1[3].Descriptor()
	// apppermission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apppermission.DefaultUpdatedAt = apppermissionDescUpdatedAt.Default.(func() time.Time)
	// apppermission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apppermission.UpdateDefaultUpdatedAt = apppermissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apppermissionDescName is the schema descriptor for name field.
	apppermissionDescName := apppermissionFields[1].Descriptor()
	// apppermission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apppermission.NameValidator = apppermissionDescName.Validators[0].(func(string) error)
	// apppermissionDescID is the schema descriptor for id field.
	apppermissionDescID := apppermissionMixinFields0[0].Descriptor()
	// apppermission.DefaultID holds the default value on creation for the id field.
	apppermission.DefaultID = apppermissionDescID.Default.(func() int)
	organizationMixin := schema.Organization{}.Mixin()
	organizationMixinHooks1 := organizationMixin[1].Hooks()
	organizationMixinHooks2 := organizationMixin[2].Hooks()
	organizationHooks := schema.Organization{}.Hooks()
	organization.Hooks[0] = organizationMixinHooks1[0]
	organization.Hooks[1] = organizationMixinHooks1[1]
	organization.Hooks[2] = organizationMixinHooks2[0]
	organization.Hooks[3] = organizationHooks[0]
	organization.Hooks[4] = organizationHooks[1]
	organization.Hooks[5] = organizationHooks[2]
	organizationMixinInters2 := organizationMixin[2].Interceptors()
	organization.Interceptors[0] = organizationMixinInters2[0]
	organizationMixinFields0 := organizationMixin[0].Fields()
	_ = organizationMixinFields0
	organizationMixinFields1 := organizationMixin[1].Fields()
	_ = organizationMixinFields1
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationMixinFields1[1].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationMixinFields1[3].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() time.Time)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationDescParentID is the schema descriptor for parent_id field.
	organizationDescParentID := organizationFields[2].Descriptor()
	// organization.DefaultParentID holds the default value on creation for the parent_id field.
	organization.DefaultParentID = organizationDescParentID.Default.(int)
	// organizationDescDomain is the schema descriptor for domain field.
	organizationDescDomain := organizationFields[3].Descriptor()
	// organization.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	organization.DomainValidator = organizationDescDomain.Validators[0].(func(string) error)
	// organizationDescCode is the schema descriptor for code field.
	organizationDescCode := organizationFields[4].Descriptor()
	// organization.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	organization.CodeValidator = organizationDescCode.Validators[0].(func(string) error)
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[5].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = organizationDescName.Validators[0].(func(string) error)
	// organizationDescCountryCode is the schema descriptor for country_code field.
	organizationDescCountryCode := organizationFields[10].Descriptor()
	// organization.CountryCodeValidator is a validator for the "country_code" field. It is called by the builders before save.
	organization.CountryCodeValidator = organizationDescCountryCode.Validators[0].(func(string) error)
	// organizationDescTimezone is the schema descriptor for timezone field.
	organizationDescTimezone := organizationFields[11].Descriptor()
	// organization.TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	organization.TimezoneValidator = organizationDescTimezone.Validators[0].(func(string) error)
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationMixinFields0[0].Descriptor()
	// organization.DefaultID holds the default value on creation for the id field.
	organization.DefaultID = organizationDescID.Default.(func() int)
	organizationuserMixin := schema.OrganizationUser{}.Mixin()
	organizationuserMixinHooks1 := organizationuserMixin[1].Hooks()
	organizationuser.Hooks[0] = organizationuserMixinHooks1[0]
	organizationuser.Hooks[1] = organizationuserMixinHooks1[1]
	organizationuserMixinFields1 := organizationuserMixin[1].Fields()
	_ = organizationuserMixinFields1
	organizationuserFields := schema.OrganizationUser{}.Fields()
	_ = organizationuserFields
	// organizationuserDescCreatedAt is the schema descriptor for created_at field.
	organizationuserDescCreatedAt := organizationuserMixinFields1[1].Descriptor()
	// organizationuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	organizationuser.DefaultCreatedAt = organizationuserDescCreatedAt.Default.(func() time.Time)
	// organizationuserDescUpdatedAt is the schema descriptor for updated_at field.
	organizationuserDescUpdatedAt := organizationuserMixinFields1[3].Descriptor()
	// organizationuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organizationuser.DefaultUpdatedAt = organizationuserDescUpdatedAt.Default.(func() time.Time)
	// organizationuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organizationuser.UpdateDefaultUpdatedAt = organizationuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinHooks1 := userMixin[1].Hooks()
	userMixinHooks2 := userMixin[2].Hooks()
	user.Hooks[0] = userMixinHooks1[0]
	user.Hooks[1] = userMixinHooks1[1]
	user.Hooks[2] = userMixinHooks2[0]
	userMixinInters2 := userMixin[2].Interceptors()
	user.Interceptors[0] = userMixinInters2[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[3].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescRegisterIP is the schema descriptor for register_ip field.
	userDescRegisterIP := userFields[4].Descriptor()
	// user.RegisterIPValidator is a validator for the "register_ip" field. It is called by the builders before save.
	user.RegisterIPValidator = userDescRegisterIP.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() int)
	userdeviceMixin := schema.UserDevice{}.Mixin()
	userdeviceMixinHooks1 := userdeviceMixin[1].Hooks()
	userdevice.Hooks[0] = userdeviceMixinHooks1[0]
	userdevice.Hooks[1] = userdeviceMixinHooks1[1]
	userdeviceMixinFields1 := userdeviceMixin[1].Fields()
	_ = userdeviceMixinFields1
	userdeviceFields := schema.UserDevice{}.Fields()
	_ = userdeviceFields
	// userdeviceDescCreatedAt is the schema descriptor for created_at field.
	userdeviceDescCreatedAt := userdeviceMixinFields1[1].Descriptor()
	// userdevice.DefaultCreatedAt holds the default value on creation for the created_at field.
	userdevice.DefaultCreatedAt = userdeviceDescCreatedAt.Default.(func() time.Time)
	// userdeviceDescUpdatedAt is the schema descriptor for updated_at field.
	userdeviceDescUpdatedAt := userdeviceMixinFields1[3].Descriptor()
	// userdevice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userdevice.DefaultUpdatedAt = userdeviceDescUpdatedAt.Default.(func() time.Time)
	// userdevice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userdevice.UpdateDefaultUpdatedAt = userdeviceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userdeviceDescDeviceUID is the schema descriptor for device_uid field.
	userdeviceDescDeviceUID := userdeviceFields[1].Descriptor()
	// userdevice.DeviceUIDValidator is a validator for the "device_uid" field. It is called by the builders before save.
	userdevice.DeviceUIDValidator = userdeviceDescDeviceUID.Validators[0].(func(string) error)
	// userdeviceDescDeviceName is the schema descriptor for device_name field.
	userdeviceDescDeviceName := userdeviceFields[2].Descriptor()
	// userdevice.DeviceNameValidator is a validator for the "device_name" field. It is called by the builders before save.
	userdevice.DeviceNameValidator = userdeviceDescDeviceName.Validators[0].(func(string) error)
	// userdeviceDescSystemName is the schema descriptor for system_name field.
	userdeviceDescSystemName := userdeviceFields[3].Descriptor()
	// userdevice.SystemNameValidator is a validator for the "system_name" field. It is called by the builders before save.
	userdevice.SystemNameValidator = userdeviceDescSystemName.Validators[0].(func(string) error)
	// userdeviceDescSystemVersion is the schema descriptor for system_version field.
	userdeviceDescSystemVersion := userdeviceFields[4].Descriptor()
	// userdevice.SystemVersionValidator is a validator for the "system_version" field. It is called by the builders before save.
	userdevice.SystemVersionValidator = userdeviceDescSystemVersion.Validators[0].(func(string) error)
	// userdeviceDescAppVersion is the schema descriptor for app_version field.
	userdeviceDescAppVersion := userdeviceFields[5].Descriptor()
	// userdevice.AppVersionValidator is a validator for the "app_version" field. It is called by the builders before save.
	userdevice.AppVersionValidator = userdeviceDescAppVersion.Validators[0].(func(string) error)
	// userdeviceDescDeviceModel is the schema descriptor for device_model field.
	userdeviceDescDeviceModel := userdeviceFields[6].Descriptor()
	// userdevice.DeviceModelValidator is a validator for the "device_model" field. It is called by the builders before save.
	userdevice.DeviceModelValidator = userdeviceDescDeviceModel.Validators[0].(func(string) error)
	useridentityMixin := schema.UserIdentity{}.Mixin()
	useridentityMixinHooks1 := useridentityMixin[1].Hooks()
	useridentity.Hooks[0] = useridentityMixinHooks1[0]
	useridentity.Hooks[1] = useridentityMixinHooks1[1]
	useridentityMixinFields1 := useridentityMixin[1].Fields()
	_ = useridentityMixinFields1
	useridentityFields := schema.UserIdentity{}.Fields()
	_ = useridentityFields
	// useridentityDescCreatedAt is the schema descriptor for created_at field.
	useridentityDescCreatedAt := useridentityMixinFields1[1].Descriptor()
	// useridentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	useridentity.DefaultCreatedAt = useridentityDescCreatedAt.Default.(func() time.Time)
	// useridentityDescUpdatedAt is the schema descriptor for updated_at field.
	useridentityDescUpdatedAt := useridentityMixinFields1[3].Descriptor()
	// useridentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	useridentity.DefaultUpdatedAt = useridentityDescUpdatedAt.Default.(func() time.Time)
	// useridentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	useridentity.UpdateDefaultUpdatedAt = useridentityDescUpdatedAt.UpdateDefault.(func() time.Time)
	userloginprofileMixin := schema.UserLoginProfile{}.Mixin()
	userloginprofileMixinHooks1 := userloginprofileMixin[1].Hooks()
	userloginprofile.Hooks[0] = userloginprofileMixinHooks1[0]
	userloginprofile.Hooks[1] = userloginprofileMixinHooks1[1]
	userloginprofileMixinFields1 := userloginprofileMixin[1].Fields()
	_ = userloginprofileMixinFields1
	userloginprofileFields := schema.UserLoginProfile{}.Fields()
	_ = userloginprofileFields
	// userloginprofileDescCreatedAt is the schema descriptor for created_at field.
	userloginprofileDescCreatedAt := userloginprofileMixinFields1[1].Descriptor()
	// userloginprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	userloginprofile.DefaultCreatedAt = userloginprofileDescCreatedAt.Default.(func() time.Time)
	// userloginprofileDescUpdatedAt is the schema descriptor for updated_at field.
	userloginprofileDescUpdatedAt := userloginprofileMixinFields1[3].Descriptor()
	// userloginprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userloginprofile.DefaultUpdatedAt = userloginprofileDescUpdatedAt.Default.(func() time.Time)
	// userloginprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userloginprofile.UpdateDefaultUpdatedAt = userloginprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userloginprofileDescMfaSecret is the schema descriptor for mfa_secret field.
	userloginprofileDescMfaSecret := userloginprofileFields[8].Descriptor()
	// userloginprofile.MfaSecretValidator is a validator for the "mfa_secret" field. It is called by the builders before save.
	userloginprofile.MfaSecretValidator = userloginprofileDescMfaSecret.Validators[0].(func(string) error)
	userpasswordMixin := schema.UserPassword{}.Mixin()
	userpasswordMixinHooks1 := userpasswordMixin[1].Hooks()
	userpassword.Hooks[0] = userpasswordMixinHooks1[0]
	userpassword.Hooks[1] = userpasswordMixinHooks1[1]
	userpasswordMixinFields1 := userpasswordMixin[1].Fields()
	_ = userpasswordMixinFields1
	userpasswordFields := schema.UserPassword{}.Fields()
	_ = userpasswordFields
	// userpasswordDescCreatedAt is the schema descriptor for created_at field.
	userpasswordDescCreatedAt := userpasswordMixinFields1[1].Descriptor()
	// userpassword.DefaultCreatedAt holds the default value on creation for the created_at field.
	userpassword.DefaultCreatedAt = userpasswordDescCreatedAt.Default.(func() time.Time)
	// userpasswordDescUpdatedAt is the schema descriptor for updated_at field.
	userpasswordDescUpdatedAt := userpasswordMixinFields1[3].Descriptor()
	// userpassword.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userpassword.DefaultUpdatedAt = userpasswordDescUpdatedAt.Default.(func() time.Time)
	// userpassword.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userpassword.UpdateDefaultUpdatedAt = userpasswordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userpasswordDescSalt is the schema descriptor for salt field.
	userpasswordDescSalt := userpasswordFields[3].Descriptor()
	// userpassword.SaltValidator is a validator for the "salt" field. It is called by the builders before save.
	userpassword.SaltValidator = userpasswordDescSalt.Validators[0].(func(string) error)
}

const (
	Version = "v0.11.8"                                         // Version of ent codegen.
	Sum     = "h1:M/M0QL1CYCUSdqGRXUrXhFYSDRJPsOOrr+RLEej/gyQ=" // Sum of ent codegen.
)
