package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/woocoos/adminx/ent"
	"github.com/woocoos/adminx/ent/user"
	"github.com/woocoos/adminx/graph/generated"
	"github.com/woocoos/adminx/graph/model"
)

// EnableDirectory is the resolver for the enableDirectory field.
func (r *mutationResolver) EnableDirectory(ctx context.Context, input model.EnableDirectoryInput) (*ent.Organization, error) {
	return r.resource.EnableOrganization(ctx, input)
}

// CreateOrganization is the resolver for the createOrganization field.
func (r *mutationResolver) CreateOrganization(ctx context.Context, input ent.CreateOrganizationInput) (*ent.Organization, error) {
	return r.resource.CreateOrganization(ctx, input)
}

// UpdateOrganization is the resolver for the updateOrganization field.
func (r *mutationResolver) UpdateOrganization(ctx context.Context, id int, input ent.UpdateOrganizationInput) (*ent.Organization, error) {
	return r.resource.UpdateOrganization(ctx, id, input)
}

// DeleteOrganization is the resolver for the deleteOrganization field.
func (r *mutationResolver) DeleteOrganization(ctx context.Context, id int) (bool, error) {
	err := r.resource.DeleteOrganization(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// CreateOrganizationAccount is the resolver for the createOrganizationAccount field.
func (r *mutationResolver) CreateOrganizationAccount(ctx context.Context, input model.CreateOrganizationAccountInput) (*ent.User, error) {
	panic(fmt.Errorf("not implemented: CreateOrganizationAccount - createOrganizationAccount"))
}

// CreateOrganizationUser is the resolver for the createOrganizationUser field.
func (r *mutationResolver) CreateOrganizationUser(ctx context.Context, id int, input ent.CreateUserInput) (*ent.User, error) {
	uid := user.DefaultID()
	input.ID = &uid
	return r.resource.CreateOrganizationUser(ctx, id, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id int, input ent.UpdateUserInput) (*ent.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// CreateApp is the resolver for the createApp field.
func (r *mutationResolver) CreateApp(ctx context.Context, input ent.CreateAppInput) (*ent.App, error) {
	panic(fmt.Errorf("not implemented: CreateApp - createApp"))
}

// UpdateApp is the resolver for the updateApp field.
func (r *mutationResolver) UpdateApp(ctx context.Context, id int, input ent.UpdateAppInput) (*ent.App, error) {
	panic(fmt.Errorf("not implemented: UpdateApp - updateApp"))
}

// DeleteApp is the resolver for the deleteApp field.
func (r *mutationResolver) DeleteApp(ctx context.Context, id int) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteApp - deleteApp"))
}

// LoginProfile is the resolver for the loginProfile field.
func (r *createUserInputResolver) LoginProfile(ctx context.Context, obj *ent.CreateUserInput, data *ent.CreateUserLoginProfileInput) error {
	if data != nil {
		data.UserID = obj.ID
		_, err := ent.FromContext(ctx).UserLoginProfile.Create().SetInput(*data).Save(ctx)
		if err != nil {
			return err
		}
		//obj.LoginProfileID = &dr.ID
	}
	return nil
}

// Password is the resolver for the password field.
func (r *createUserInputResolver) Password(ctx context.Context, obj *ent.CreateUserInput, data *ent.CreateUserPasswordInput) error {
	if data != nil {
		data.UserID = obj.ID
		_, err := r.resource.CreateUserPassword(ctx, data)
		if err != nil {
			return err
		}
	}
	//obj.PasswordIDs = append(obj.PasswordIDs, up.ID)
	return nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
