// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppColumns holds the columns for the "app" table.
	AppColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_by", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 45},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 45},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"web", "native", "server"}},
		{Name: "redirect_uri", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "app_key", Type: field.TypeString, Nullable: true},
		{Name: "app_secret", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "scopes", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "token_validity", Type: field.TypeInt32, Nullable: true},
		{Name: "refresh_token_validity", Type: field.TypeInt32, Nullable: true},
		{Name: "logo", Type: field.TypeString, Nullable: true},
		{Name: "comments", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Enums: []string{"active", "inactive"}},
	}
	// AppTable holds the schema information for the "app" table.
	AppTable = &schema.Table{
		Name:       "app",
		Columns:    AppColumns,
		PrimaryKey: []*schema.Column{AppColumns[0]},
	}
	// AppMenuColumns holds the columns for the "app_menu" table.
	AppMenuColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_by", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "parent_id", Type: field.TypeInt},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"dir", "menu"}},
		{Name: "name", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "comments", Type: field.TypeString, Nullable: true},
		{Name: "display_sort", Type: field.TypeInt32, Nullable: true},
		{Name: "app_id", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "permission_id", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
	}
	// AppMenuTable holds the schema information for the "app_menu" table.
	AppMenuTable = &schema.Table{
		Name:       "app_menu",
		Columns:    AppMenuColumns,
		PrimaryKey: []*schema.Column{AppMenuColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "app_menu_app_menus",
				Columns:    []*schema.Column{AppMenuColumns[10]},
				RefColumns: []*schema.Column{AppColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "app_menu_app_permission_menus",
				Columns:    []*schema.Column{AppMenuColumns[11]},
				RefColumns: []*schema.Column{AppPermissionColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AppPermissionColumns holds the columns for the "app_permission" table.
	AppPermissionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_by", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "kind", Type: field.TypeEnum, Nullable: true, Enums: []string{"read", "write", "list"}},
		{Name: "comments", Type: field.TypeString, Nullable: true},
		{Name: "app_id", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
	}
	// AppPermissionTable holds the schema information for the "app_permission" table.
	AppPermissionTable = &schema.Table{
		Name:       "app_permission",
		Columns:    AppPermissionColumns,
		PrimaryKey: []*schema.Column{AppPermissionColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "app_permission_app_permissions",
				Columns:    []*schema.Column{AppPermissionColumns[8]},
				RefColumns: []*schema.Column{AppColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// OrganizationColumns holds the columns for the "organization" table.
	OrganizationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_by", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "kind", Type: field.TypeEnum, Nullable: true, Enums: []string{"root", "org"}},
		{Name: "domain", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "code", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "profile", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Enums: []string{"active", "inactive"}},
		{Name: "path", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "display_sort", Type: field.TypeInt32, Nullable: true},
		{Name: "country_code", Type: field.TypeString, Nullable: true, Size: 10},
		{Name: "timezone", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true, Default: 0, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "owner_id", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
	}
	// OrganizationTable holds the schema information for the "organization" table.
	OrganizationTable = &schema.Table{
		Name:       "organization",
		Columns:    OrganizationColumns,
		PrimaryKey: []*schema.Column{OrganizationColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organization_organization_children",
				Columns:    []*schema.Column{OrganizationColumns[16]},
				RefColumns: []*schema.Column{OrganizationColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "organization_user_owner",
				Columns:    []*schema.Column{OrganizationColumns[17]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OrganizationUserColumns holds the columns for the "organization_user" table.
	OrganizationUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "created_by", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "user_id", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
	}
	// OrganizationUserTable holds the schema information for the "organization_user" table.
	OrganizationUserTable = &schema.Table{
		Name:       "organization_user",
		Columns:    OrganizationUserColumns,
		PrimaryKey: []*schema.Column{OrganizationUserColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organization_user_organization_organization",
				Columns:    []*schema.Column{OrganizationUserColumns[6]},
				RefColumns: []*schema.Column{OrganizationColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "organization_user_user_user",
				Columns:    []*schema.Column{OrganizationUserColumns[7]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organizationuser_org_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{OrganizationUserColumns[6], OrganizationUserColumns[7]},
			},
		},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_by", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "principal_name", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "user_type", Type: field.TypeEnum, Enums: []string{"account", "member"}},
		{Name: "creation_type", Type: field.TypeEnum, Enums: []string{"invitation", "register", "manual"}},
		{Name: "register_ip", Type: field.TypeString, Size: 45},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Enums: []string{"processing", "active", "inactive"}},
		{Name: "comments", Type: field.TypeString, Nullable: true},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// UserDeviceColumns holds the columns for the "user_device" table.
	UserDeviceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "created_by", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "device_uid", Type: field.TypeString, Size: 64},
		{Name: "device_name", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "system_name", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "system_version", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "app_version", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "device_model", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Enums: []string{"active", "inactive"}},
		{Name: "comments", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
	}
	// UserDeviceTable holds the schema information for the "user_device" table.
	UserDeviceTable = &schema.Table{
		Name:       "user_device",
		Columns:    UserDeviceColumns,
		PrimaryKey: []*schema.Column{UserDeviceColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_device_user_devices",
				Columns:    []*schema.Column{UserDeviceColumns[13]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UserIdentityColumns holds the columns for the "user_identity" table.
	UserIdentityColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "created_by", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"name", "email", "phone", "wechat", "qq"}},
		{Name: "code", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "code_extend", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Enums: []string{"verify", "active", "inactive"}},
		{Name: "user_id", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
	}
	// UserIdentityTable holds the schema information for the "user_identity" table.
	UserIdentityTable = &schema.Table{
		Name:       "user_identity",
		Columns:    UserIdentityColumns,
		PrimaryKey: []*schema.Column{UserIdentityColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_identity_user_identities",
				Columns:    []*schema.Column{UserIdentityColumns[9]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UserLoginProfileColumns holds the columns for the "user_login_profile" table.
	UserLoginProfileColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "created_by", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_login_ip", Type: field.TypeString, Nullable: true},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "can_login", Type: field.TypeBool, Nullable: true},
		{Name: "set_kind", Type: field.TypeEnum, Enums: []string{"keep", "customer", "auto"}},
		{Name: "password_reset", Type: field.TypeBool, Nullable: true},
		{Name: "verify_device", Type: field.TypeBool},
		{Name: "mfa_enabled", Type: field.TypeBool, Nullable: true},
		{Name: "mfa_secret", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "mfa_status", Type: field.TypeEnum, Nullable: true, Enums: []string{"enable", "inactive"}},
		{Name: "user_id", Type: field.TypeInt, Unique: true, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
	}
	// UserLoginProfileTable holds the schema information for the "user_login_profile" table.
	UserLoginProfileTable = &schema.Table{
		Name:       "user_login_profile",
		Columns:    UserLoginProfileColumns,
		PrimaryKey: []*schema.Column{UserLoginProfileColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_login_profile_user_login_profile",
				Columns:    []*schema.Column{UserLoginProfileColumns[14]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UserPasswordColumns holds the columns for the "user_password" table.
	UserPasswordColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "created_by", Type: field.TypeInt, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "scene", Type: field.TypeEnum, Nullable: true, Enums: []string{"login"}},
		{Name: "password", Type: field.TypeString, Nullable: true},
		{Name: "salt", Type: field.TypeString, Size: 45},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Enums: []string{"inactive"}},
		{Name: "memo", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"mysql": "bigint"}},
	}
	// UserPasswordTable holds the schema information for the "user_password" table.
	UserPasswordTable = &schema.Table{
		Name:       "user_password",
		Columns:    UserPasswordColumns,
		PrimaryKey: []*schema.Column{UserPasswordColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_password_user_passwords",
				Columns:    []*schema.Column{UserPasswordColumns[10]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppTable,
		AppMenuTable,
		AppPermissionTable,
		OrganizationTable,
		OrganizationUserTable,
		UserTable,
		UserDeviceTable,
		UserIdentityTable,
		UserLoginProfileTable,
		UserPasswordTable,
	}
)

func init() {
	AppTable.Annotation = &entsql.Annotation{
		Table: "app",
	}
	AppMenuTable.ForeignKeys[0].RefTable = AppTable
	AppMenuTable.ForeignKeys[1].RefTable = AppPermissionTable
	AppMenuTable.Annotation = &entsql.Annotation{
		Table: "app_menu",
	}
	AppPermissionTable.ForeignKeys[0].RefTable = AppTable
	AppPermissionTable.Annotation = &entsql.Annotation{
		Table: "app_permission",
	}
	OrganizationTable.ForeignKeys[0].RefTable = OrganizationTable
	OrganizationTable.ForeignKeys[1].RefTable = UserTable
	OrganizationTable.Annotation = &entsql.Annotation{
		Table: "organization",
	}
	OrganizationUserTable.ForeignKeys[0].RefTable = OrganizationTable
	OrganizationUserTable.ForeignKeys[1].RefTable = UserTable
	OrganizationUserTable.Annotation = &entsql.Annotation{
		Table: "organization_user",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
	UserDeviceTable.ForeignKeys[0].RefTable = UserTable
	UserDeviceTable.Annotation = &entsql.Annotation{
		Table: "user_device",
	}
	UserIdentityTable.ForeignKeys[0].RefTable = UserTable
	UserIdentityTable.Annotation = &entsql.Annotation{
		Table: "user_identity",
	}
	UserLoginProfileTable.ForeignKeys[0].RefTable = UserTable
	UserLoginProfileTable.Annotation = &entsql.Annotation{
		Table: "user_login_profile",
	}
	UserPasswordTable.ForeignKeys[0].RefTable = UserTable
	UserPasswordTable.Annotation = &entsql.Annotation{
		Table: "user_password",
	}
}
