// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/adminx/ent/app"
	"github.com/woocoos/adminx/ent/appmenu"
	"github.com/woocoos/adminx/ent/apppermission"
	"github.com/woocoos/adminx/ent/predicate"
)

// AppMenuUpdate is the builder for updating AppMenu entities.
type AppMenuUpdate struct {
	config
	hooks    []Hook
	mutation *AppMenuMutation
}

// Where appends a list predicates to the AppMenuUpdate builder.
func (amu *AppMenuUpdate) Where(ps ...predicate.AppMenu) *AppMenuUpdate {
	amu.mutation.Where(ps...)
	return amu
}

// SetUpdatedBy sets the "updated_by" field.
func (amu *AppMenuUpdate) SetUpdatedBy(i int) *AppMenuUpdate {
	amu.mutation.ResetUpdatedBy()
	amu.mutation.SetUpdatedBy(i)
	return amu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (amu *AppMenuUpdate) SetNillableUpdatedBy(i *int) *AppMenuUpdate {
	if i != nil {
		amu.SetUpdatedBy(*i)
	}
	return amu
}

// AddUpdatedBy adds i to the "updated_by" field.
func (amu *AppMenuUpdate) AddUpdatedBy(i int) *AppMenuUpdate {
	amu.mutation.AddUpdatedBy(i)
	return amu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (amu *AppMenuUpdate) ClearUpdatedBy() *AppMenuUpdate {
	amu.mutation.ClearUpdatedBy()
	return amu
}

// SetUpdatedAt sets the "updated_at" field.
func (amu *AppMenuUpdate) SetUpdatedAt(t time.Time) *AppMenuUpdate {
	amu.mutation.SetUpdatedAt(t)
	return amu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (amu *AppMenuUpdate) ClearUpdatedAt() *AppMenuUpdate {
	amu.mutation.ClearUpdatedAt()
	return amu
}

// SetAppID sets the "app_id" field.
func (amu *AppMenuUpdate) SetAppID(i int) *AppMenuUpdate {
	amu.mutation.SetAppID(i)
	return amu
}

// SetParentID sets the "parent_id" field.
func (amu *AppMenuUpdate) SetParentID(i int) *AppMenuUpdate {
	amu.mutation.ResetParentID()
	amu.mutation.SetParentID(i)
	return amu
}

// AddParentID adds i to the "parent_id" field.
func (amu *AppMenuUpdate) AddParentID(i int) *AppMenuUpdate {
	amu.mutation.AddParentID(i)
	return amu
}

// SetKind sets the "kind" field.
func (amu *AppMenuUpdate) SetKind(a appmenu.Kind) *AppMenuUpdate {
	amu.mutation.SetKind(a)
	return amu
}

// SetName sets the "name" field.
func (amu *AppMenuUpdate) SetName(s string) *AppMenuUpdate {
	amu.mutation.SetName(s)
	return amu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (amu *AppMenuUpdate) SetNillableName(s *string) *AppMenuUpdate {
	if s != nil {
		amu.SetName(*s)
	}
	return amu
}

// ClearName clears the value of the "name" field.
func (amu *AppMenuUpdate) ClearName() *AppMenuUpdate {
	amu.mutation.ClearName()
	return amu
}

// SetPermissionID sets the "permission_id" field.
func (amu *AppMenuUpdate) SetPermissionID(i int) *AppMenuUpdate {
	amu.mutation.SetPermissionID(i)
	return amu
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (amu *AppMenuUpdate) SetNillablePermissionID(i *int) *AppMenuUpdate {
	if i != nil {
		amu.SetPermissionID(*i)
	}
	return amu
}

// ClearPermissionID clears the value of the "permission_id" field.
func (amu *AppMenuUpdate) ClearPermissionID() *AppMenuUpdate {
	amu.mutation.ClearPermissionID()
	return amu
}

// SetComments sets the "comments" field.
func (amu *AppMenuUpdate) SetComments(s string) *AppMenuUpdate {
	amu.mutation.SetComments(s)
	return amu
}

// SetNillableComments sets the "comments" field if the given value is not nil.
func (amu *AppMenuUpdate) SetNillableComments(s *string) *AppMenuUpdate {
	if s != nil {
		amu.SetComments(*s)
	}
	return amu
}

// ClearComments clears the value of the "comments" field.
func (amu *AppMenuUpdate) ClearComments() *AppMenuUpdate {
	amu.mutation.ClearComments()
	return amu
}

// SetDisplaySort sets the "display_sort" field.
func (amu *AppMenuUpdate) SetDisplaySort(i int32) *AppMenuUpdate {
	amu.mutation.ResetDisplaySort()
	amu.mutation.SetDisplaySort(i)
	return amu
}

// SetNillableDisplaySort sets the "display_sort" field if the given value is not nil.
func (amu *AppMenuUpdate) SetNillableDisplaySort(i *int32) *AppMenuUpdate {
	if i != nil {
		amu.SetDisplaySort(*i)
	}
	return amu
}

// AddDisplaySort adds i to the "display_sort" field.
func (amu *AppMenuUpdate) AddDisplaySort(i int32) *AppMenuUpdate {
	amu.mutation.AddDisplaySort(i)
	return amu
}

// ClearDisplaySort clears the value of the "display_sort" field.
func (amu *AppMenuUpdate) ClearDisplaySort() *AppMenuUpdate {
	amu.mutation.ClearDisplaySort()
	return amu
}

// SetApp sets the "app" edge to the App entity.
func (amu *AppMenuUpdate) SetApp(a *App) *AppMenuUpdate {
	return amu.SetAppID(a.ID)
}

// SetPermission sets the "permission" edge to the AppPermission entity.
func (amu *AppMenuUpdate) SetPermission(a *AppPermission) *AppMenuUpdate {
	return amu.SetPermissionID(a.ID)
}

// Mutation returns the AppMenuMutation object of the builder.
func (amu *AppMenuUpdate) Mutation() *AppMenuMutation {
	return amu.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (amu *AppMenuUpdate) ClearApp() *AppMenuUpdate {
	amu.mutation.ClearApp()
	return amu
}

// ClearPermission clears the "permission" edge to the AppPermission entity.
func (amu *AppMenuUpdate) ClearPermission() *AppMenuUpdate {
	amu.mutation.ClearPermission()
	return amu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (amu *AppMenuUpdate) Save(ctx context.Context) (int, error) {
	if err := amu.defaults(); err != nil {
		return 0, err
	}
	return withHooks[int, AppMenuMutation](ctx, amu.sqlSave, amu.mutation, amu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (amu *AppMenuUpdate) SaveX(ctx context.Context) int {
	affected, err := amu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (amu *AppMenuUpdate) Exec(ctx context.Context) error {
	_, err := amu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (amu *AppMenuUpdate) ExecX(ctx context.Context) {
	if err := amu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (amu *AppMenuUpdate) defaults() error {
	if _, ok := amu.mutation.UpdatedAt(); !ok && !amu.mutation.UpdatedAtCleared() {
		if appmenu.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized appmenu.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := appmenu.UpdateDefaultUpdatedAt()
		amu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (amu *AppMenuUpdate) check() error {
	if v, ok := amu.mutation.Kind(); ok {
		if err := appmenu.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "AppMenu.kind": %w`, err)}
		}
	}
	if v, ok := amu.mutation.Name(); ok {
		if err := appmenu.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AppMenu.name": %w`, err)}
		}
	}
	if _, ok := amu.mutation.AppID(); amu.mutation.AppCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "AppMenu.app"`)
	}
	return nil
}

func (amu *AppMenuUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := amu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(appmenu.Table, appmenu.Columns, sqlgraph.NewFieldSpec(appmenu.FieldID, field.TypeInt))
	if ps := amu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := amu.mutation.UpdatedBy(); ok {
		_spec.SetField(appmenu.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := amu.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(appmenu.FieldUpdatedBy, field.TypeInt, value)
	}
	if amu.mutation.UpdatedByCleared() {
		_spec.ClearField(appmenu.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := amu.mutation.UpdatedAt(); ok {
		_spec.SetField(appmenu.FieldUpdatedAt, field.TypeTime, value)
	}
	if amu.mutation.UpdatedAtCleared() {
		_spec.ClearField(appmenu.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := amu.mutation.ParentID(); ok {
		_spec.SetField(appmenu.FieldParentID, field.TypeInt, value)
	}
	if value, ok := amu.mutation.AddedParentID(); ok {
		_spec.AddField(appmenu.FieldParentID, field.TypeInt, value)
	}
	if value, ok := amu.mutation.Kind(); ok {
		_spec.SetField(appmenu.FieldKind, field.TypeEnum, value)
	}
	if value, ok := amu.mutation.Name(); ok {
		_spec.SetField(appmenu.FieldName, field.TypeString, value)
	}
	if amu.mutation.NameCleared() {
		_spec.ClearField(appmenu.FieldName, field.TypeString)
	}
	if value, ok := amu.mutation.Comments(); ok {
		_spec.SetField(appmenu.FieldComments, field.TypeString, value)
	}
	if amu.mutation.CommentsCleared() {
		_spec.ClearField(appmenu.FieldComments, field.TypeString)
	}
	if value, ok := amu.mutation.DisplaySort(); ok {
		_spec.SetField(appmenu.FieldDisplaySort, field.TypeInt32, value)
	}
	if value, ok := amu.mutation.AddedDisplaySort(); ok {
		_spec.AddField(appmenu.FieldDisplaySort, field.TypeInt32, value)
	}
	if amu.mutation.DisplaySortCleared() {
		_spec.ClearField(appmenu.FieldDisplaySort, field.TypeInt32)
	}
	if amu.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appmenu.AppTable,
			Columns: []string{appmenu.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: app.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := amu.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appmenu.AppTable,
			Columns: []string{appmenu.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: app.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if amu.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appmenu.PermissionTable,
			Columns: []string{appmenu.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: apppermission.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := amu.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appmenu.PermissionTable,
			Columns: []string{appmenu.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: apppermission.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, amu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appmenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	amu.mutation.done = true
	return n, nil
}

// AppMenuUpdateOne is the builder for updating a single AppMenu entity.
type AppMenuUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppMenuMutation
}

// SetUpdatedBy sets the "updated_by" field.
func (amuo *AppMenuUpdateOne) SetUpdatedBy(i int) *AppMenuUpdateOne {
	amuo.mutation.ResetUpdatedBy()
	amuo.mutation.SetUpdatedBy(i)
	return amuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (amuo *AppMenuUpdateOne) SetNillableUpdatedBy(i *int) *AppMenuUpdateOne {
	if i != nil {
		amuo.SetUpdatedBy(*i)
	}
	return amuo
}

// AddUpdatedBy adds i to the "updated_by" field.
func (amuo *AppMenuUpdateOne) AddUpdatedBy(i int) *AppMenuUpdateOne {
	amuo.mutation.AddUpdatedBy(i)
	return amuo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (amuo *AppMenuUpdateOne) ClearUpdatedBy() *AppMenuUpdateOne {
	amuo.mutation.ClearUpdatedBy()
	return amuo
}

// SetUpdatedAt sets the "updated_at" field.
func (amuo *AppMenuUpdateOne) SetUpdatedAt(t time.Time) *AppMenuUpdateOne {
	amuo.mutation.SetUpdatedAt(t)
	return amuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (amuo *AppMenuUpdateOne) ClearUpdatedAt() *AppMenuUpdateOne {
	amuo.mutation.ClearUpdatedAt()
	return amuo
}

// SetAppID sets the "app_id" field.
func (amuo *AppMenuUpdateOne) SetAppID(i int) *AppMenuUpdateOne {
	amuo.mutation.SetAppID(i)
	return amuo
}

// SetParentID sets the "parent_id" field.
func (amuo *AppMenuUpdateOne) SetParentID(i int) *AppMenuUpdateOne {
	amuo.mutation.ResetParentID()
	amuo.mutation.SetParentID(i)
	return amuo
}

// AddParentID adds i to the "parent_id" field.
func (amuo *AppMenuUpdateOne) AddParentID(i int) *AppMenuUpdateOne {
	amuo.mutation.AddParentID(i)
	return amuo
}

// SetKind sets the "kind" field.
func (amuo *AppMenuUpdateOne) SetKind(a appmenu.Kind) *AppMenuUpdateOne {
	amuo.mutation.SetKind(a)
	return amuo
}

// SetName sets the "name" field.
func (amuo *AppMenuUpdateOne) SetName(s string) *AppMenuUpdateOne {
	amuo.mutation.SetName(s)
	return amuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (amuo *AppMenuUpdateOne) SetNillableName(s *string) *AppMenuUpdateOne {
	if s != nil {
		amuo.SetName(*s)
	}
	return amuo
}

// ClearName clears the value of the "name" field.
func (amuo *AppMenuUpdateOne) ClearName() *AppMenuUpdateOne {
	amuo.mutation.ClearName()
	return amuo
}

// SetPermissionID sets the "permission_id" field.
func (amuo *AppMenuUpdateOne) SetPermissionID(i int) *AppMenuUpdateOne {
	amuo.mutation.SetPermissionID(i)
	return amuo
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (amuo *AppMenuUpdateOne) SetNillablePermissionID(i *int) *AppMenuUpdateOne {
	if i != nil {
		amuo.SetPermissionID(*i)
	}
	return amuo
}

// ClearPermissionID clears the value of the "permission_id" field.
func (amuo *AppMenuUpdateOne) ClearPermissionID() *AppMenuUpdateOne {
	amuo.mutation.ClearPermissionID()
	return amuo
}

// SetComments sets the "comments" field.
func (amuo *AppMenuUpdateOne) SetComments(s string) *AppMenuUpdateOne {
	amuo.mutation.SetComments(s)
	return amuo
}

// SetNillableComments sets the "comments" field if the given value is not nil.
func (amuo *AppMenuUpdateOne) SetNillableComments(s *string) *AppMenuUpdateOne {
	if s != nil {
		amuo.SetComments(*s)
	}
	return amuo
}

// ClearComments clears the value of the "comments" field.
func (amuo *AppMenuUpdateOne) ClearComments() *AppMenuUpdateOne {
	amuo.mutation.ClearComments()
	return amuo
}

// SetDisplaySort sets the "display_sort" field.
func (amuo *AppMenuUpdateOne) SetDisplaySort(i int32) *AppMenuUpdateOne {
	amuo.mutation.ResetDisplaySort()
	amuo.mutation.SetDisplaySort(i)
	return amuo
}

// SetNillableDisplaySort sets the "display_sort" field if the given value is not nil.
func (amuo *AppMenuUpdateOne) SetNillableDisplaySort(i *int32) *AppMenuUpdateOne {
	if i != nil {
		amuo.SetDisplaySort(*i)
	}
	return amuo
}

// AddDisplaySort adds i to the "display_sort" field.
func (amuo *AppMenuUpdateOne) AddDisplaySort(i int32) *AppMenuUpdateOne {
	amuo.mutation.AddDisplaySort(i)
	return amuo
}

// ClearDisplaySort clears the value of the "display_sort" field.
func (amuo *AppMenuUpdateOne) ClearDisplaySort() *AppMenuUpdateOne {
	amuo.mutation.ClearDisplaySort()
	return amuo
}

// SetApp sets the "app" edge to the App entity.
func (amuo *AppMenuUpdateOne) SetApp(a *App) *AppMenuUpdateOne {
	return amuo.SetAppID(a.ID)
}

// SetPermission sets the "permission" edge to the AppPermission entity.
func (amuo *AppMenuUpdateOne) SetPermission(a *AppPermission) *AppMenuUpdateOne {
	return amuo.SetPermissionID(a.ID)
}

// Mutation returns the AppMenuMutation object of the builder.
func (amuo *AppMenuUpdateOne) Mutation() *AppMenuMutation {
	return amuo.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (amuo *AppMenuUpdateOne) ClearApp() *AppMenuUpdateOne {
	amuo.mutation.ClearApp()
	return amuo
}

// ClearPermission clears the "permission" edge to the AppPermission entity.
func (amuo *AppMenuUpdateOne) ClearPermission() *AppMenuUpdateOne {
	amuo.mutation.ClearPermission()
	return amuo
}

// Where appends a list predicates to the AppMenuUpdate builder.
func (amuo *AppMenuUpdateOne) Where(ps ...predicate.AppMenu) *AppMenuUpdateOne {
	amuo.mutation.Where(ps...)
	return amuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (amuo *AppMenuUpdateOne) Select(field string, fields ...string) *AppMenuUpdateOne {
	amuo.fields = append([]string{field}, fields...)
	return amuo
}

// Save executes the query and returns the updated AppMenu entity.
func (amuo *AppMenuUpdateOne) Save(ctx context.Context) (*AppMenu, error) {
	if err := amuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks[*AppMenu, AppMenuMutation](ctx, amuo.sqlSave, amuo.mutation, amuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (amuo *AppMenuUpdateOne) SaveX(ctx context.Context) *AppMenu {
	node, err := amuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (amuo *AppMenuUpdateOne) Exec(ctx context.Context) error {
	_, err := amuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (amuo *AppMenuUpdateOne) ExecX(ctx context.Context) {
	if err := amuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (amuo *AppMenuUpdateOne) defaults() error {
	if _, ok := amuo.mutation.UpdatedAt(); !ok && !amuo.mutation.UpdatedAtCleared() {
		if appmenu.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized appmenu.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := appmenu.UpdateDefaultUpdatedAt()
		amuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (amuo *AppMenuUpdateOne) check() error {
	if v, ok := amuo.mutation.Kind(); ok {
		if err := appmenu.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "AppMenu.kind": %w`, err)}
		}
	}
	if v, ok := amuo.mutation.Name(); ok {
		if err := appmenu.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AppMenu.name": %w`, err)}
		}
	}
	if _, ok := amuo.mutation.AppID(); amuo.mutation.AppCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "AppMenu.app"`)
	}
	return nil
}

func (amuo *AppMenuUpdateOne) sqlSave(ctx context.Context) (_node *AppMenu, err error) {
	if err := amuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(appmenu.Table, appmenu.Columns, sqlgraph.NewFieldSpec(appmenu.FieldID, field.TypeInt))
	id, ok := amuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppMenu.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := amuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appmenu.FieldID)
		for _, f := range fields {
			if !appmenu.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appmenu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := amuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := amuo.mutation.UpdatedBy(); ok {
		_spec.SetField(appmenu.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := amuo.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(appmenu.FieldUpdatedBy, field.TypeInt, value)
	}
	if amuo.mutation.UpdatedByCleared() {
		_spec.ClearField(appmenu.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := amuo.mutation.UpdatedAt(); ok {
		_spec.SetField(appmenu.FieldUpdatedAt, field.TypeTime, value)
	}
	if amuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(appmenu.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := amuo.mutation.ParentID(); ok {
		_spec.SetField(appmenu.FieldParentID, field.TypeInt, value)
	}
	if value, ok := amuo.mutation.AddedParentID(); ok {
		_spec.AddField(appmenu.FieldParentID, field.TypeInt, value)
	}
	if value, ok := amuo.mutation.Kind(); ok {
		_spec.SetField(appmenu.FieldKind, field.TypeEnum, value)
	}
	if value, ok := amuo.mutation.Name(); ok {
		_spec.SetField(appmenu.FieldName, field.TypeString, value)
	}
	if amuo.mutation.NameCleared() {
		_spec.ClearField(appmenu.FieldName, field.TypeString)
	}
	if value, ok := amuo.mutation.Comments(); ok {
		_spec.SetField(appmenu.FieldComments, field.TypeString, value)
	}
	if amuo.mutation.CommentsCleared() {
		_spec.ClearField(appmenu.FieldComments, field.TypeString)
	}
	if value, ok := amuo.mutation.DisplaySort(); ok {
		_spec.SetField(appmenu.FieldDisplaySort, field.TypeInt32, value)
	}
	if value, ok := amuo.mutation.AddedDisplaySort(); ok {
		_spec.AddField(appmenu.FieldDisplaySort, field.TypeInt32, value)
	}
	if amuo.mutation.DisplaySortCleared() {
		_spec.ClearField(appmenu.FieldDisplaySort, field.TypeInt32)
	}
	if amuo.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appmenu.AppTable,
			Columns: []string{appmenu.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: app.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := amuo.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appmenu.AppTable,
			Columns: []string{appmenu.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: app.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if amuo.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appmenu.PermissionTable,
			Columns: []string{appmenu.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: apppermission.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := amuo.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appmenu.PermissionTable,
			Columns: []string{appmenu.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: apppermission.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AppMenu{config: amuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, amuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appmenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	amuo.mutation.done = true
	return _node, nil
}
