// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/adminx/ent/apppermission"
	"github.com/woocoos/adminx/ent/predicate"
)

// AppPermissionDelete is the builder for deleting a AppPermission entity.
type AppPermissionDelete struct {
	config
	hooks    []Hook
	mutation *AppPermissionMutation
}

// Where appends a list predicates to the AppPermissionDelete builder.
func (apd *AppPermissionDelete) Where(ps ...predicate.AppPermission) *AppPermissionDelete {
	apd.mutation.Where(ps...)
	return apd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (apd *AppPermissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, AppPermissionMutation](ctx, apd.sqlExec, apd.mutation, apd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (apd *AppPermissionDelete) ExecX(ctx context.Context) int {
	n, err := apd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (apd *AppPermissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(apppermission.Table, sqlgraph.NewFieldSpec(apppermission.FieldID, field.TypeInt))
	if ps := apd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, apd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	apd.mutation.done = true
	return affected, err
}

// AppPermissionDeleteOne is the builder for deleting a single AppPermission entity.
type AppPermissionDeleteOne struct {
	apd *AppPermissionDelete
}

// Where appends a list predicates to the AppPermissionDelete builder.
func (apdo *AppPermissionDeleteOne) Where(ps ...predicate.AppPermission) *AppPermissionDeleteOne {
	apdo.apd.mutation.Where(ps...)
	return apdo
}

// Exec executes the deletion query.
func (apdo *AppPermissionDeleteOne) Exec(ctx context.Context) error {
	n, err := apdo.apd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{apppermission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (apdo *AppPermissionDeleteOne) ExecX(ctx context.Context) {
	if err := apdo.Exec(ctx); err != nil {
		panic(err)
	}
}
