// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/adminx/ent/app"
	"github.com/woocoos/adminx/ent/appmenu"
	"github.com/woocoos/adminx/ent/apppermission"
	"github.com/woocoos/adminx/ent/predicate"
)

// AppPermissionQuery is the builder for querying AppPermission entities.
type AppPermissionQuery struct {
	config
	ctx            *QueryContext
	order          []OrderFunc
	inters         []Interceptor
	predicates     []predicate.AppPermission
	withApp        *AppQuery
	withMenus      *AppMenuQuery
	modifiers      []func(*sql.Selector)
	loadTotal      []func(context.Context, []*AppPermission) error
	withNamedMenus map[string]*AppMenuQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppPermissionQuery builder.
func (apq *AppPermissionQuery) Where(ps ...predicate.AppPermission) *AppPermissionQuery {
	apq.predicates = append(apq.predicates, ps...)
	return apq
}

// Limit the number of records to be returned by this query.
func (apq *AppPermissionQuery) Limit(limit int) *AppPermissionQuery {
	apq.ctx.Limit = &limit
	return apq
}

// Offset to start from.
func (apq *AppPermissionQuery) Offset(offset int) *AppPermissionQuery {
	apq.ctx.Offset = &offset
	return apq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (apq *AppPermissionQuery) Unique(unique bool) *AppPermissionQuery {
	apq.ctx.Unique = &unique
	return apq
}

// Order specifies how the records should be ordered.
func (apq *AppPermissionQuery) Order(o ...OrderFunc) *AppPermissionQuery {
	apq.order = append(apq.order, o...)
	return apq
}

// QueryApp chains the current query on the "app" edge.
func (apq *AppPermissionQuery) QueryApp() *AppQuery {
	query := (&AppClient{config: apq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := apq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := apq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(apppermission.Table, apppermission.FieldID, selector),
			sqlgraph.To(app.Table, app.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, apppermission.AppTable, apppermission.AppColumn),
		)
		fromU = sqlgraph.SetNeighbors(apq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMenus chains the current query on the "menus" edge.
func (apq *AppPermissionQuery) QueryMenus() *AppMenuQuery {
	query := (&AppMenuClient{config: apq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := apq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := apq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(apppermission.Table, apppermission.FieldID, selector),
			sqlgraph.To(appmenu.Table, appmenu.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, apppermission.MenusTable, apppermission.MenusColumn),
		)
		fromU = sqlgraph.SetNeighbors(apq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AppPermission entity from the query.
// Returns a *NotFoundError when no AppPermission was found.
func (apq *AppPermissionQuery) First(ctx context.Context) (*AppPermission, error) {
	nodes, err := apq.Limit(1).All(setContextOp(ctx, apq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{apppermission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (apq *AppPermissionQuery) FirstX(ctx context.Context) *AppPermission {
	node, err := apq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppPermission ID from the query.
// Returns a *NotFoundError when no AppPermission ID was found.
func (apq *AppPermissionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = apq.Limit(1).IDs(setContextOp(ctx, apq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{apppermission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (apq *AppPermissionQuery) FirstIDX(ctx context.Context) int {
	id, err := apq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppPermission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AppPermission entity is found.
// Returns a *NotFoundError when no AppPermission entities are found.
func (apq *AppPermissionQuery) Only(ctx context.Context) (*AppPermission, error) {
	nodes, err := apq.Limit(2).All(setContextOp(ctx, apq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{apppermission.Label}
	default:
		return nil, &NotSingularError{apppermission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (apq *AppPermissionQuery) OnlyX(ctx context.Context) *AppPermission {
	node, err := apq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppPermission ID in the query.
// Returns a *NotSingularError when more than one AppPermission ID is found.
// Returns a *NotFoundError when no entities are found.
func (apq *AppPermissionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = apq.Limit(2).IDs(setContextOp(ctx, apq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{apppermission.Label}
	default:
		err = &NotSingularError{apppermission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (apq *AppPermissionQuery) OnlyIDX(ctx context.Context) int {
	id, err := apq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppPermissions.
func (apq *AppPermissionQuery) All(ctx context.Context) ([]*AppPermission, error) {
	ctx = setContextOp(ctx, apq.ctx, "All")
	if err := apq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AppPermission, *AppPermissionQuery]()
	return withInterceptors[[]*AppPermission](ctx, apq, qr, apq.inters)
}

// AllX is like All, but panics if an error occurs.
func (apq *AppPermissionQuery) AllX(ctx context.Context) []*AppPermission {
	nodes, err := apq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppPermission IDs.
func (apq *AppPermissionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if apq.ctx.Unique == nil && apq.path != nil {
		apq.Unique(true)
	}
	ctx = setContextOp(ctx, apq.ctx, "IDs")
	if err = apq.Select(apppermission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (apq *AppPermissionQuery) IDsX(ctx context.Context) []int {
	ids, err := apq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (apq *AppPermissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, apq.ctx, "Count")
	if err := apq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, apq, querierCount[*AppPermissionQuery](), apq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (apq *AppPermissionQuery) CountX(ctx context.Context) int {
	count, err := apq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (apq *AppPermissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, apq.ctx, "Exist")
	switch _, err := apq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (apq *AppPermissionQuery) ExistX(ctx context.Context) bool {
	exist, err := apq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppPermissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (apq *AppPermissionQuery) Clone() *AppPermissionQuery {
	if apq == nil {
		return nil
	}
	return &AppPermissionQuery{
		config:     apq.config,
		ctx:        apq.ctx.Clone(),
		order:      append([]OrderFunc{}, apq.order...),
		inters:     append([]Interceptor{}, apq.inters...),
		predicates: append([]predicate.AppPermission{}, apq.predicates...),
		withApp:    apq.withApp.Clone(),
		withMenus:  apq.withMenus.Clone(),
		// clone intermediate query.
		sql:  apq.sql.Clone(),
		path: apq.path,
	}
}

// WithApp tells the query-builder to eager-load the nodes that are connected to
// the "app" edge. The optional arguments are used to configure the query builder of the edge.
func (apq *AppPermissionQuery) WithApp(opts ...func(*AppQuery)) *AppPermissionQuery {
	query := (&AppClient{config: apq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	apq.withApp = query
	return apq
}

// WithMenus tells the query-builder to eager-load the nodes that are connected to
// the "menus" edge. The optional arguments are used to configure the query builder of the edge.
func (apq *AppPermissionQuery) WithMenus(opts ...func(*AppMenuQuery)) *AppPermissionQuery {
	query := (&AppMenuClient{config: apq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	apq.withMenus = query
	return apq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedBy int `json:"created_by,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppPermission.Query().
//		GroupBy(apppermission.FieldCreatedBy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (apq *AppPermissionQuery) GroupBy(field string, fields ...string) *AppPermissionGroupBy {
	apq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AppPermissionGroupBy{build: apq}
	grbuild.flds = &apq.ctx.Fields
	grbuild.label = apppermission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedBy int `json:"created_by,omitempty"`
//	}
//
//	client.AppPermission.Query().
//		Select(apppermission.FieldCreatedBy).
//		Scan(ctx, &v)
func (apq *AppPermissionQuery) Select(fields ...string) *AppPermissionSelect {
	apq.ctx.Fields = append(apq.ctx.Fields, fields...)
	sbuild := &AppPermissionSelect{AppPermissionQuery: apq}
	sbuild.label = apppermission.Label
	sbuild.flds, sbuild.scan = &apq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AppPermissionSelect configured with the given aggregations.
func (apq *AppPermissionQuery) Aggregate(fns ...AggregateFunc) *AppPermissionSelect {
	return apq.Select().Aggregate(fns...)
}

func (apq *AppPermissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range apq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, apq); err != nil {
				return err
			}
		}
	}
	for _, f := range apq.ctx.Fields {
		if !apppermission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if apq.path != nil {
		prev, err := apq.path(ctx)
		if err != nil {
			return err
		}
		apq.sql = prev
	}
	return nil
}

func (apq *AppPermissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AppPermission, error) {
	var (
		nodes       = []*AppPermission{}
		_spec       = apq.querySpec()
		loadedTypes = [2]bool{
			apq.withApp != nil,
			apq.withMenus != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AppPermission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AppPermission{config: apq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(apq.modifiers) > 0 {
		_spec.Modifiers = apq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, apq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := apq.withApp; query != nil {
		if err := apq.loadApp(ctx, query, nodes, nil,
			func(n *AppPermission, e *App) { n.Edges.App = e }); err != nil {
			return nil, err
		}
	}
	if query := apq.withMenus; query != nil {
		if err := apq.loadMenus(ctx, query, nodes,
			func(n *AppPermission) { n.Edges.Menus = []*AppMenu{} },
			func(n *AppPermission, e *AppMenu) { n.Edges.Menus = append(n.Edges.Menus, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range apq.withNamedMenus {
		if err := apq.loadMenus(ctx, query, nodes,
			func(n *AppPermission) { n.appendNamedMenus(name) },
			func(n *AppPermission, e *AppMenu) { n.appendNamedMenus(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range apq.loadTotal {
		if err := apq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (apq *AppPermissionQuery) loadApp(ctx context.Context, query *AppQuery, nodes []*AppPermission, init func(*AppPermission), assign func(*AppPermission, *App)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AppPermission)
	for i := range nodes {
		fk := nodes[i].AppID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(app.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "app_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (apq *AppPermissionQuery) loadMenus(ctx context.Context, query *AppMenuQuery, nodes []*AppPermission, init func(*AppPermission), assign func(*AppPermission, *AppMenu)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AppPermission)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.AppMenu(func(s *sql.Selector) {
		s.Where(sql.InValues(apppermission.MenusColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PermissionID
		if fk == nil {
			return fmt.Errorf(`foreign-key "permission_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "permission_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (apq *AppPermissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := apq.querySpec()
	if len(apq.modifiers) > 0 {
		_spec.Modifiers = apq.modifiers
	}
	_spec.Node.Columns = apq.ctx.Fields
	if len(apq.ctx.Fields) > 0 {
		_spec.Unique = apq.ctx.Unique != nil && *apq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, apq.driver, _spec)
}

func (apq *AppPermissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(apppermission.Table, apppermission.Columns, sqlgraph.NewFieldSpec(apppermission.FieldID, field.TypeInt))
	_spec.From = apq.sql
	if unique := apq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if apq.path != nil {
		_spec.Unique = true
	}
	if fields := apq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apppermission.FieldID)
		for i := range fields {
			if fields[i] != apppermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := apq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := apq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := apq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := apq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (apq *AppPermissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(apq.driver.Dialect())
	t1 := builder.Table(apppermission.Table)
	columns := apq.ctx.Fields
	if len(columns) == 0 {
		columns = apppermission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if apq.sql != nil {
		selector = apq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if apq.ctx.Unique != nil && *apq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range apq.predicates {
		p(selector)
	}
	for _, p := range apq.order {
		p(selector)
	}
	if offset := apq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := apq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedMenus tells the query-builder to eager-load the nodes that are connected to the "menus"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (apq *AppPermissionQuery) WithNamedMenus(name string, opts ...func(*AppMenuQuery)) *AppPermissionQuery {
	query := (&AppMenuClient{config: apq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if apq.withNamedMenus == nil {
		apq.withNamedMenus = make(map[string]*AppMenuQuery)
	}
	apq.withNamedMenus[name] = query
	return apq
}

// AppPermissionGroupBy is the group-by builder for AppPermission entities.
type AppPermissionGroupBy struct {
	selector
	build *AppPermissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (apgb *AppPermissionGroupBy) Aggregate(fns ...AggregateFunc) *AppPermissionGroupBy {
	apgb.fns = append(apgb.fns, fns...)
	return apgb
}

// Scan applies the selector query and scans the result into the given value.
func (apgb *AppPermissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, apgb.build.ctx, "GroupBy")
	if err := apgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AppPermissionQuery, *AppPermissionGroupBy](ctx, apgb.build, apgb, apgb.build.inters, v)
}

func (apgb *AppPermissionGroupBy) sqlScan(ctx context.Context, root *AppPermissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(apgb.fns))
	for _, fn := range apgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*apgb.flds)+len(apgb.fns))
		for _, f := range *apgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*apgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := apgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AppPermissionSelect is the builder for selecting fields of AppPermission entities.
type AppPermissionSelect struct {
	*AppPermissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aps *AppPermissionSelect) Aggregate(fns ...AggregateFunc) *AppPermissionSelect {
	aps.fns = append(aps.fns, fns...)
	return aps
}

// Scan applies the selector query and scans the result into the given value.
func (aps *AppPermissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aps.ctx, "Select")
	if err := aps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AppPermissionQuery, *AppPermissionSelect](ctx, aps.AppPermissionQuery, aps, aps.inters, v)
}

func (aps *AppPermissionSelect) sqlScan(ctx context.Context, root *AppPermissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aps.fns))
	for _, fn := range aps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
