// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/adminx/ent/organizationpolicy"
	"github.com/woocoos/adminx/ent/predicate"
	"github.com/woocoos/adminx/graph/entgen/types"
)

// OrganizationPolicyUpdate is the builder for updating OrganizationPolicy entities.
type OrganizationPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationPolicyMutation
}

// Where appends a list predicates to the OrganizationPolicyUpdate builder.
func (opu *OrganizationPolicyUpdate) Where(ps ...predicate.OrganizationPolicy) *OrganizationPolicyUpdate {
	opu.mutation.Where(ps...)
	return opu
}

// SetOrgID sets the "org_id" field.
func (opu *OrganizationPolicyUpdate) SetOrgID(i int) *OrganizationPolicyUpdate {
	opu.mutation.ResetOrgID()
	opu.mutation.SetOrgID(i)
	return opu
}

// AddOrgID adds i to the "org_id" field.
func (opu *OrganizationPolicyUpdate) AddOrgID(i int) *OrganizationPolicyUpdate {
	opu.mutation.AddOrgID(i)
	return opu
}

// SetAppID sets the "app_id" field.
func (opu *OrganizationPolicyUpdate) SetAppID(i int) *OrganizationPolicyUpdate {
	opu.mutation.ResetAppID()
	opu.mutation.SetAppID(i)
	return opu
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (opu *OrganizationPolicyUpdate) SetNillableAppID(i *int) *OrganizationPolicyUpdate {
	if i != nil {
		opu.SetAppID(*i)
	}
	return opu
}

// AddAppID adds i to the "app_id" field.
func (opu *OrganizationPolicyUpdate) AddAppID(i int) *OrganizationPolicyUpdate {
	opu.mutation.AddAppID(i)
	return opu
}

// ClearAppID clears the value of the "app_id" field.
func (opu *OrganizationPolicyUpdate) ClearAppID() *OrganizationPolicyUpdate {
	opu.mutation.ClearAppID()
	return opu
}

// SetAppPolicyID sets the "app_policy_id" field.
func (opu *OrganizationPolicyUpdate) SetAppPolicyID(i int) *OrganizationPolicyUpdate {
	opu.mutation.ResetAppPolicyID()
	opu.mutation.SetAppPolicyID(i)
	return opu
}

// SetNillableAppPolicyID sets the "app_policy_id" field if the given value is not nil.
func (opu *OrganizationPolicyUpdate) SetNillableAppPolicyID(i *int) *OrganizationPolicyUpdate {
	if i != nil {
		opu.SetAppPolicyID(*i)
	}
	return opu
}

// AddAppPolicyID adds i to the "app_policy_id" field.
func (opu *OrganizationPolicyUpdate) AddAppPolicyID(i int) *OrganizationPolicyUpdate {
	opu.mutation.AddAppPolicyID(i)
	return opu
}

// ClearAppPolicyID clears the value of the "app_policy_id" field.
func (opu *OrganizationPolicyUpdate) ClearAppPolicyID() *OrganizationPolicyUpdate {
	opu.mutation.ClearAppPolicyID()
	return opu
}

// SetName sets the "name" field.
func (opu *OrganizationPolicyUpdate) SetName(s string) *OrganizationPolicyUpdate {
	opu.mutation.SetName(s)
	return opu
}

// SetComments sets the "comments" field.
func (opu *OrganizationPolicyUpdate) SetComments(s string) *OrganizationPolicyUpdate {
	opu.mutation.SetComments(s)
	return opu
}

// SetRules sets the "rules" field.
func (opu *OrganizationPolicyUpdate) SetRules(tr []types.PolicyRule) *OrganizationPolicyUpdate {
	opu.mutation.SetRules(tr)
	return opu
}

// AppendRules appends tr to the "rules" field.
func (opu *OrganizationPolicyUpdate) AppendRules(tr []types.PolicyRule) *OrganizationPolicyUpdate {
	opu.mutation.AppendRules(tr)
	return opu
}

// Mutation returns the OrganizationPolicyMutation object of the builder.
func (opu *OrganizationPolicyUpdate) Mutation() *OrganizationPolicyMutation {
	return opu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (opu *OrganizationPolicyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, OrganizationPolicyMutation](ctx, opu.sqlSave, opu.mutation, opu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (opu *OrganizationPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := opu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (opu *OrganizationPolicyUpdate) Exec(ctx context.Context) error {
	_, err := opu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opu *OrganizationPolicyUpdate) ExecX(ctx context.Context) {
	if err := opu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (opu *OrganizationPolicyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(organizationpolicy.Table, organizationpolicy.Columns, sqlgraph.NewFieldSpec(organizationpolicy.FieldID, field.TypeInt))
	if ps := opu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := opu.mutation.OrgID(); ok {
		_spec.SetField(organizationpolicy.FieldOrgID, field.TypeInt, value)
	}
	if value, ok := opu.mutation.AddedOrgID(); ok {
		_spec.AddField(organizationpolicy.FieldOrgID, field.TypeInt, value)
	}
	if value, ok := opu.mutation.AppID(); ok {
		_spec.SetField(organizationpolicy.FieldAppID, field.TypeInt, value)
	}
	if value, ok := opu.mutation.AddedAppID(); ok {
		_spec.AddField(organizationpolicy.FieldAppID, field.TypeInt, value)
	}
	if opu.mutation.AppIDCleared() {
		_spec.ClearField(organizationpolicy.FieldAppID, field.TypeInt)
	}
	if value, ok := opu.mutation.AppPolicyID(); ok {
		_spec.SetField(organizationpolicy.FieldAppPolicyID, field.TypeInt, value)
	}
	if value, ok := opu.mutation.AddedAppPolicyID(); ok {
		_spec.AddField(organizationpolicy.FieldAppPolicyID, field.TypeInt, value)
	}
	if opu.mutation.AppPolicyIDCleared() {
		_spec.ClearField(organizationpolicy.FieldAppPolicyID, field.TypeInt)
	}
	if value, ok := opu.mutation.Name(); ok {
		_spec.SetField(organizationpolicy.FieldName, field.TypeString, value)
	}
	if value, ok := opu.mutation.Comments(); ok {
		_spec.SetField(organizationpolicy.FieldComments, field.TypeString, value)
	}
	if value, ok := opu.mutation.Rules(); ok {
		_spec.SetField(organizationpolicy.FieldRules, field.TypeJSON, value)
	}
	if value, ok := opu.mutation.AppendedRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, organizationpolicy.FieldRules, value)
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, opu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	opu.mutation.done = true
	return n, nil
}

// OrganizationPolicyUpdateOne is the builder for updating a single OrganizationPolicy entity.
type OrganizationPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationPolicyMutation
}

// SetOrgID sets the "org_id" field.
func (opuo *OrganizationPolicyUpdateOne) SetOrgID(i int) *OrganizationPolicyUpdateOne {
	opuo.mutation.ResetOrgID()
	opuo.mutation.SetOrgID(i)
	return opuo
}

// AddOrgID adds i to the "org_id" field.
func (opuo *OrganizationPolicyUpdateOne) AddOrgID(i int) *OrganizationPolicyUpdateOne {
	opuo.mutation.AddOrgID(i)
	return opuo
}

// SetAppID sets the "app_id" field.
func (opuo *OrganizationPolicyUpdateOne) SetAppID(i int) *OrganizationPolicyUpdateOne {
	opuo.mutation.ResetAppID()
	opuo.mutation.SetAppID(i)
	return opuo
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (opuo *OrganizationPolicyUpdateOne) SetNillableAppID(i *int) *OrganizationPolicyUpdateOne {
	if i != nil {
		opuo.SetAppID(*i)
	}
	return opuo
}

// AddAppID adds i to the "app_id" field.
func (opuo *OrganizationPolicyUpdateOne) AddAppID(i int) *OrganizationPolicyUpdateOne {
	opuo.mutation.AddAppID(i)
	return opuo
}

// ClearAppID clears the value of the "app_id" field.
func (opuo *OrganizationPolicyUpdateOne) ClearAppID() *OrganizationPolicyUpdateOne {
	opuo.mutation.ClearAppID()
	return opuo
}

// SetAppPolicyID sets the "app_policy_id" field.
func (opuo *OrganizationPolicyUpdateOne) SetAppPolicyID(i int) *OrganizationPolicyUpdateOne {
	opuo.mutation.ResetAppPolicyID()
	opuo.mutation.SetAppPolicyID(i)
	return opuo
}

// SetNillableAppPolicyID sets the "app_policy_id" field if the given value is not nil.
func (opuo *OrganizationPolicyUpdateOne) SetNillableAppPolicyID(i *int) *OrganizationPolicyUpdateOne {
	if i != nil {
		opuo.SetAppPolicyID(*i)
	}
	return opuo
}

// AddAppPolicyID adds i to the "app_policy_id" field.
func (opuo *OrganizationPolicyUpdateOne) AddAppPolicyID(i int) *OrganizationPolicyUpdateOne {
	opuo.mutation.AddAppPolicyID(i)
	return opuo
}

// ClearAppPolicyID clears the value of the "app_policy_id" field.
func (opuo *OrganizationPolicyUpdateOne) ClearAppPolicyID() *OrganizationPolicyUpdateOne {
	opuo.mutation.ClearAppPolicyID()
	return opuo
}

// SetName sets the "name" field.
func (opuo *OrganizationPolicyUpdateOne) SetName(s string) *OrganizationPolicyUpdateOne {
	opuo.mutation.SetName(s)
	return opuo
}

// SetComments sets the "comments" field.
func (opuo *OrganizationPolicyUpdateOne) SetComments(s string) *OrganizationPolicyUpdateOne {
	opuo.mutation.SetComments(s)
	return opuo
}

// SetRules sets the "rules" field.
func (opuo *OrganizationPolicyUpdateOne) SetRules(tr []types.PolicyRule) *OrganizationPolicyUpdateOne {
	opuo.mutation.SetRules(tr)
	return opuo
}

// AppendRules appends tr to the "rules" field.
func (opuo *OrganizationPolicyUpdateOne) AppendRules(tr []types.PolicyRule) *OrganizationPolicyUpdateOne {
	opuo.mutation.AppendRules(tr)
	return opuo
}

// Mutation returns the OrganizationPolicyMutation object of the builder.
func (opuo *OrganizationPolicyUpdateOne) Mutation() *OrganizationPolicyMutation {
	return opuo.mutation
}

// Where appends a list predicates to the OrganizationPolicyUpdate builder.
func (opuo *OrganizationPolicyUpdateOne) Where(ps ...predicate.OrganizationPolicy) *OrganizationPolicyUpdateOne {
	opuo.mutation.Where(ps...)
	return opuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (opuo *OrganizationPolicyUpdateOne) Select(field string, fields ...string) *OrganizationPolicyUpdateOne {
	opuo.fields = append([]string{field}, fields...)
	return opuo
}

// Save executes the query and returns the updated OrganizationPolicy entity.
func (opuo *OrganizationPolicyUpdateOne) Save(ctx context.Context) (*OrganizationPolicy, error) {
	return withHooks[*OrganizationPolicy, OrganizationPolicyMutation](ctx, opuo.sqlSave, opuo.mutation, opuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (opuo *OrganizationPolicyUpdateOne) SaveX(ctx context.Context) *OrganizationPolicy {
	node, err := opuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (opuo *OrganizationPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := opuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opuo *OrganizationPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := opuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (opuo *OrganizationPolicyUpdateOne) sqlSave(ctx context.Context) (_node *OrganizationPolicy, err error) {
	_spec := sqlgraph.NewUpdateSpec(organizationpolicy.Table, organizationpolicy.Columns, sqlgraph.NewFieldSpec(organizationpolicy.FieldID, field.TypeInt))
	id, ok := opuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrganizationPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := opuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationpolicy.FieldID)
		for _, f := range fields {
			if !organizationpolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organizationpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := opuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := opuo.mutation.OrgID(); ok {
		_spec.SetField(organizationpolicy.FieldOrgID, field.TypeInt, value)
	}
	if value, ok := opuo.mutation.AddedOrgID(); ok {
		_spec.AddField(organizationpolicy.FieldOrgID, field.TypeInt, value)
	}
	if value, ok := opuo.mutation.AppID(); ok {
		_spec.SetField(organizationpolicy.FieldAppID, field.TypeInt, value)
	}
	if value, ok := opuo.mutation.AddedAppID(); ok {
		_spec.AddField(organizationpolicy.FieldAppID, field.TypeInt, value)
	}
	if opuo.mutation.AppIDCleared() {
		_spec.ClearField(organizationpolicy.FieldAppID, field.TypeInt)
	}
	if value, ok := opuo.mutation.AppPolicyID(); ok {
		_spec.SetField(organizationpolicy.FieldAppPolicyID, field.TypeInt, value)
	}
	if value, ok := opuo.mutation.AddedAppPolicyID(); ok {
		_spec.AddField(organizationpolicy.FieldAppPolicyID, field.TypeInt, value)
	}
	if opuo.mutation.AppPolicyIDCleared() {
		_spec.ClearField(organizationpolicy.FieldAppPolicyID, field.TypeInt)
	}
	if value, ok := opuo.mutation.Name(); ok {
		_spec.SetField(organizationpolicy.FieldName, field.TypeString, value)
	}
	if value, ok := opuo.mutation.Comments(); ok {
		_spec.SetField(organizationpolicy.FieldComments, field.TypeString, value)
	}
	if value, ok := opuo.mutation.Rules(); ok {
		_spec.SetField(organizationpolicy.FieldRules, field.TypeJSON, value)
	}
	if value, ok := opuo.mutation.AppendedRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, organizationpolicy.FieldRules, value)
		})
	}
	_node = &OrganizationPolicy{config: opuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, opuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	opuo.mutation.done = true
	return _node, nil
}
