// Code generated by ent, DO NOT EDIT.

package organizationpolicy

const (
	// Label holds the string label denoting the organizationpolicy type in the database.
	Label = "organization_policy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrgID holds the string denoting the org_id field in the database.
	FieldOrgID = "org_id"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldAppPolicyID holds the string denoting the app_policy_id field in the database.
	FieldAppPolicyID = "app_policy_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldComments holds the string denoting the comments field in the database.
	FieldComments = "comments"
	// FieldRules holds the string denoting the rules field in the database.
	FieldRules = "rules"
	// Table holds the table name of the organizationpolicy in the database.
	Table = "organization_policy"
)

// Columns holds all SQL columns for organizationpolicy fields.
var Columns = []string{
	FieldID,
	FieldOrgID,
	FieldAppID,
	FieldAppPolicyID,
	FieldName,
	FieldComments,
	FieldRules,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
