// Code generated by ent, DO NOT EDIT.

package organizationpolicy

import (
	"entgo.io/ent/dialect/sql"
	"github.com/woocoos/adminx/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLTE(FieldID, id))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldOrgID, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldAppID, v))
}

// AppPolicyID applies equality check predicate on the "app_policy_id" field. It's identical to AppPolicyIDEQ.
func AppPolicyID(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldAppPolicyID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldName, v))
}

// Comments applies equality check predicate on the "comments" field. It's identical to CommentsEQ.
func Comments(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldComments, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLTE(FieldOrgID, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLTE(FieldAppID, v))
}

// AppIDIsNil applies the IsNil predicate on the "app_id" field.
func AppIDIsNil() predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldIsNull(FieldAppID))
}

// AppIDNotNil applies the NotNil predicate on the "app_id" field.
func AppIDNotNil() predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNotNull(FieldAppID))
}

// AppPolicyIDEQ applies the EQ predicate on the "app_policy_id" field.
func AppPolicyIDEQ(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldAppPolicyID, v))
}

// AppPolicyIDNEQ applies the NEQ predicate on the "app_policy_id" field.
func AppPolicyIDNEQ(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNEQ(FieldAppPolicyID, v))
}

// AppPolicyIDIn applies the In predicate on the "app_policy_id" field.
func AppPolicyIDIn(vs ...int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldIn(FieldAppPolicyID, vs...))
}

// AppPolicyIDNotIn applies the NotIn predicate on the "app_policy_id" field.
func AppPolicyIDNotIn(vs ...int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNotIn(FieldAppPolicyID, vs...))
}

// AppPolicyIDGT applies the GT predicate on the "app_policy_id" field.
func AppPolicyIDGT(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGT(FieldAppPolicyID, v))
}

// AppPolicyIDGTE applies the GTE predicate on the "app_policy_id" field.
func AppPolicyIDGTE(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGTE(FieldAppPolicyID, v))
}

// AppPolicyIDLT applies the LT predicate on the "app_policy_id" field.
func AppPolicyIDLT(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLT(FieldAppPolicyID, v))
}

// AppPolicyIDLTE applies the LTE predicate on the "app_policy_id" field.
func AppPolicyIDLTE(v int) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLTE(FieldAppPolicyID, v))
}

// AppPolicyIDIsNil applies the IsNil predicate on the "app_policy_id" field.
func AppPolicyIDIsNil() predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldIsNull(FieldAppPolicyID))
}

// AppPolicyIDNotNil applies the NotNil predicate on the "app_policy_id" field.
func AppPolicyIDNotNil() predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNotNull(FieldAppPolicyID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldContainsFold(FieldName, v))
}

// CommentsEQ applies the EQ predicate on the "comments" field.
func CommentsEQ(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEQ(FieldComments, v))
}

// CommentsNEQ applies the NEQ predicate on the "comments" field.
func CommentsNEQ(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNEQ(FieldComments, v))
}

// CommentsIn applies the In predicate on the "comments" field.
func CommentsIn(vs ...string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldIn(FieldComments, vs...))
}

// CommentsNotIn applies the NotIn predicate on the "comments" field.
func CommentsNotIn(vs ...string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldNotIn(FieldComments, vs...))
}

// CommentsGT applies the GT predicate on the "comments" field.
func CommentsGT(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGT(FieldComments, v))
}

// CommentsGTE applies the GTE predicate on the "comments" field.
func CommentsGTE(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldGTE(FieldComments, v))
}

// CommentsLT applies the LT predicate on the "comments" field.
func CommentsLT(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLT(FieldComments, v))
}

// CommentsLTE applies the LTE predicate on the "comments" field.
func CommentsLTE(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldLTE(FieldComments, v))
}

// CommentsContains applies the Contains predicate on the "comments" field.
func CommentsContains(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldContains(FieldComments, v))
}

// CommentsHasPrefix applies the HasPrefix predicate on the "comments" field.
func CommentsHasPrefix(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldHasPrefix(FieldComments, v))
}

// CommentsHasSuffix applies the HasSuffix predicate on the "comments" field.
func CommentsHasSuffix(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldHasSuffix(FieldComments, v))
}

// CommentsEqualFold applies the EqualFold predicate on the "comments" field.
func CommentsEqualFold(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldEqualFold(FieldComments, v))
}

// CommentsContainsFold applies the ContainsFold predicate on the "comments" field.
func CommentsContainsFold(v string) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(sql.FieldContainsFold(FieldComments, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrganizationPolicy) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrganizationPolicy) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrganizationPolicy) predicate.OrganizationPolicy {
	return predicate.OrganizationPolicy(func(s *sql.Selector) {
		p(s.Not())
	})
}
